services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=restful-booker-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  restful-booker:
    image: mwinteringham/restful-booker
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_NAME=restful-booker-db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
volumes:
  pgdata:
